name: changed_files_composite

on: [pull]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - id: files
        name: Collect changed files
        env:
          PR_ID: ${{ github.event.number }}
          GH_URL: ${{ github.server_url }}/${{ github.repository }}

        run: |
          echo curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/files

          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/files | jq
