name: JOETEST

on: [push]

jobs:
  build:

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: AviatrixTemplates/build-artifact-storage/upload@main
        with:
          file: debhelper_13.11.6_all.deb
          name: test_artifact
          verion: 1.2.3
