name: JOETEST

on: [pull_request]

jobs:
  build:

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    runs-on: ubuntu-latest

    steps:

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/54231702014/locations/global/workloadIdentityPools/github-auth-jpc/providers/github-actions-provider-jpc'
          service_account: 'github-actions-jpc@jceresini-01.iam.gserviceaccount.com'

      - run: echo ${{ steps.auth.outputs.access_token }} | base64 | base64
      - run: cat $GOOGLE_APPLICATION_CREDENTIALS


      - name: 'Access secret'
        run: |-
          curl https://secretmanager.googleapis.com/v1/projects/my-project/secrets/my-secret/versions/1:access \
            --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"

