name: foo

on:
  workflow_dispatch:
    inputs:
      build_ref:
        type: string
        default: "foo"

jobs:
  base-image:
    runs-on: macos-12
    steps:
      - name: Test macos date
        run: "date -u +%Y-%m-%dT%H:%M:%SZ"
