name: farts

on:
  workflow_dispatch:
    inputs:
      build_ref:
        type: string
        default: "foo"

jobs:
  base-image:
    runs-on: macos-12
    steps:
      - name: Test foo (${{ github.ref }})
        run: env

      - name: Checkout branch we're building (${{ inputs.build_ref }})
        run: env

