name: JOETEST

on: [push]

env:
  GITHUB_API_TOKEN: ${{ secrets.SOME_SECRET }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:


      - id: files
        name: Collect changed files
        uses: jitterbit/get-changed-files@v1
        # this step can error but still collect files
        continue-on-error: true

      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done

      - name: Changed Files
        id: changed-files
        uses: jceresini/get-changed-files@v1


      - run: |
          for file in ${{ steps.changed-files.outputs.all }}; do
            echo "Do something with this ${file}."
          done

